### ISSUE TITLE
stochastic_reduce_precision formula

### ISSUE THREAD

**Issue by PierrickPochelu** [Vivswan/AnalogVNN#15]
Hello,

First of all, thank you for publishing AnalogVNN implementation

I am comparing your implementation with the original paper: https://arxiv.org/pdf/2210.10048.pdf

As far I know, I have seen a difference which is maybe a mistake:

https://github.com/Vivswan/AnalogVNN/blob/94a09b7232cf10ef7d22c5e7517eb4a74baf1fd9/analogvnn/fn/reduce_precision.py#L44

stochastic_reduce_precision formula is:
-  In the original paper, page 24, named "SRP" : [arxiv link original paper](https://arxiv.org/pdf/2210.10048.pdf) . **"r" follows an uniform distribution between 0 and 1**
- In your code :  **"rand_x" follows a normal distribution** centered on 0 with 1 as std of the shape g. There the documentation of randn_like: [doc torch randn_like](https://pytorch.org/docs/stable/generated/torch.randn_like.html?highlight=randn#torch.randn_like).

I think we should  use "torch.distributions.uniform.Uniform" instead of "torch.randn_like" https://pytorch.org/docs/stable/distributions.html?highlight=uniform#torch.distributions.uniform.Uniform

**Comment by Vivswan** [comment]
In PyTorch there are two different functions: 
- [torch.randn_like](https://pytorch.org/docs/stable/generated/torch.randn_like.html) which uses normal distribution
- [torch.rand_like](https://pytorch.org/docs/stable/generated/torch.rand_like.html), which uses uniform distribution (used in the code)

Thanks for reporting the issue.
Pls free feel to report more issue or ask questions.
