### ISSUE TITLE
Can't reproduce the graph of the paper

### ISSUE THREAD

**Issue by hatsuka20** [Vivswan/AnalogVNN#69]
We tested your sample code. However, we couldn't reproduce your results.

For example, we manualy set a `std` of `GaussianNoise` as 0.0, 0.1, ..., 0.4 in the MNIST 3-Linear sample code. But an accuracy of the model did not increase. 

How do we reproduce the results?

![image](https://github.com/Vivswan/AnalogVNN/assets/31998467/9abe6077-1a73-4e85-adbb-a70a92566186)

Thank you.

**Comment by Vivswan** [comment]
Did you have reduce precision layers in your model?

The std of gaussian noise layer was based on this equation (where leakage is same as error probability):
https://github.com/Vivswan/AnalogVNN/blob/b639108b1e996d535eb292677a23e5a12908bb61/analogvnn/nn/noise/GaussianNoise.py#L75-L75

**Comment by Vivswan** [comment]
if you still have issues you reopen this or email me

**Comment by hatsuka20** [comment]
@Vivswan 

Thank you for your reply.

> The sample code for creating this type of architecture is present in: https://github.com/Vivswan/AnalogVNN/blob/master/sample_code.py

We experimented exactly on your sample code. The only change was to manually and directly set variables in the `GaussianNoise` module called and imported by that sample code. But we couldn't get desired results.

So, how do we reproduce the results such the paper's figures by using that sample code?

**Comment by Vivswan** [comment]
[AnalogVNN-Research-main.zip](https://github.com/user-attachments/files/16094792/AnalogVNN-Research-main.zip)

This was the code use to create those figures. check out `crc/analog_vnn_1_model.py` for 1-6 layer model and `crc/parneet_model.py` for 9-layer model

Keep in mind, there are 1000s of models variations i trained which took a lot of compute and time.
unfortunately I can't find the output data produced by these models else I would have save you a lot of time.

if it possible for you tell me the what specifically you are trying to test or recreate I can guide to that, which may save you some time.
